// Offline trainer for the alignment-memory frequency table (align_freq).
//
// Fetches pinned canonical USFM (ULT/UST, from api/data/canonical.json) off
// DCS, walks the gold `\zaln-s` alignment milestones, and counts how often each
// source Strong's number aligns to each target English surface — both single
// words AND the full contiguous phrase a milestone covers (e.g. "the earth").
// Emits scripts/out/align-freq.sql.
//
// This is wordMAP's "alignment memory" reduced to per-token frequencies —
// computed here in Node so the Cloudflare Worker can serve suggestions with a
// single indexed D1 lookup instead of running an aligner at request time
// (Workers have no filesystem and ~128 MB; they can't host the engine). The
// model only changes when a new canonical version publishes: bump the ref in
// canonical.json, re-run this, apply the SQL.
//
// The corpus-parsing primitives (book numbers, normalization, the gold-walk)
// live in scripts/lib/align-corpus.mjs so the eval harness builds an identical
// model. Run (from worktree root):
//   node scripts/train-aligner.mjs                 # curated default set
//   node scripts/train-aligner.mjs --all-ot        # all OT books in the release
//   node scripts/train-aligner.mjs --all-ot --nt   # whole released Bible
//   node scripts/train-aligner.mjs ZEC MAL         # explicit books
// Then apply:
//   npm run db:align:local       # local dev D1
//   npm run db:align:remote      # production D1

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import usfm from "usfm-js";
import {
  BOOK_NUMBERS, OT_BOOKS, NT_BOOKS, SEP, SPACE, walkAlign,
} from "./lib/align-corpus.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const DEFAULT_SET = [
  "GEN", "EXO", "PSA", "ISA", "JER",
  "HOS", "JOL", "AMO", "OBA", "JON", "MIC", "NAM", "HAB", "ZEP", "HAG", "ZEC", "MAL",
];

const manifest = JSON.parse(
  readFileSync(resolve(repoRoot, "api/data/canonical.json"), "utf8"),
);

const args = process.argv.slice(2);
let books = [];
if (args.includes("--all-ot")) books = books.concat(OT_BOOKS);
if (args.includes("--nt")) books = books.concat(NT_BOOKS);
const explicit = args.filter((a) => !a.startsWith("--")).map((b) => b.toUpperCase());
if (explicit.length) books = explicit;
if (books.length === 0) books = DEFAULT_SET;

const counts = new Map();

for (const res of manifest.resources) {
  const alignedOt = [];
  const alignedNt = [];
  for (const book of books) {
    const num = BOOK_NUMBERS[book];
    if (!num) {
      console.warn(`  unknown book: ${book}`);
      continue;
    }
    const url = `https://git.door43.org/${res.repo}/raw/${res.ref}/${num}-${book}.usfm`;
    process.stdout.write(`  ${res.bible} ${book} ... `);
    let r;
    try {
      r = await fetch(url);
    } catch (e) {
      console.log(`fetch failed (${e?.message ?? e}) - skip`);
      continue;
    }
    if (!r.ok) {
      console.log(`${r.status} - not in release, skip`);
      continue;
    }
    const json = usfm.toJSON(await r.text());
    const stats = { pairs: 0 };
    let vCount = 0;
    for (const ch of Object.values(json.chapters || {})) {
      for (const v of Object.values(ch)) {
        walkAlign(v.verseObjects || [], [], res.bible, counts, stats);
        vCount++;
      }
    }
    // A book present in the release but not yet word-aligned contributes no
    // \zaln-s pairs — exclude it so the model reflects only released+aligned
    // canon (the actual basis for suggestions).
    if (stats.pairs === 0) {
      console.log(`${vCount} verses, 0 aligned - skip (not yet aligned)`);
      continue;
    }
    (+num <= 39 ? alignedOt : alignedNt).push(book);
    console.log(`ok (${vCount} verses, ${stats.pairs} aligned words)`);
  }
  console.log(
    `${res.bible}: ${alignedOt.length + alignedNt.length} aligned books (OT ${alignedOt.length}, NT ${alignedNt.length})`,
  );
  console.log(`  OT aligned: ${alignedOt.join(SPACE) || "(none)"}`);
}

const esc = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const VALSEP = "," + SPACE;
const lines = [
  "-- Auto-generated by scripts/train-aligner.mjs. Do not edit by hand.",
  `-- Generated: ${new Date().toISOString()}`,
  `-- bibles: ${manifest.resources.map((r) => r.bible).join(VALSEP)}`,
  `-- books: ${books.join(SPACE)}`,
  "DELETE FROM align_freq;",
];
const entries = [...counts.entries()];
let phraseRows = 0;
const BATCH = 100;
for (let i = 0; i < entries.length; i += BATCH) {
  const batch = entries.slice(i, i + BATCH);
  lines.push("INSERT OR REPLACE INTO align_freq (bible, strong, surface, count) VALUES");
  lines.push(
    batch
      .map(([k, c]) => {
        const [bible, strong, surface] = k.split(SEP);
        if (surface.indexOf(SPACE) >= 0) phraseRows++;
        return "(" + [esc(bible), esc(strong), esc(surface), c].join(VALSEP) + ")";
      })
      .join("," + "\n") + ";",
  );
}

const outDir = resolve(repoRoot, "scripts/out");
mkdirSync(outDir, { recursive: true });
const outPath = resolve(outDir, "align-freq.sql");
writeFileSync(outPath, lines.join("\n") + "\n");
console.log(`\nwrote ${outPath}`);
console.log(`  ${entries.length} rows (${phraseRows} phrase, ${entries.length - phraseRows} single-word)`);
console.log(`  ${(lines.join("\n").length / 1024 / 1024).toFixed(2)} MB`);
console.log("\nApply: npm run db:align:local   (or db:align:remote for production)");
